### ISSUE TITLE
Allow sorting of peripheral registers by address

### ISSUE THREAD

**Issue by Spaark84** [microsoft/vscode-embedded-tools#10]
Allow the sorting of the peripheral registers and the register bit fields by address in addition to sorting by name. Sorting by name may be confusing if one looks a the MCU reference manual.

**Comment by robotdad** [comment]
We discussed this one and it is a similar issue as #14. If we enabled a sort by address, we would have to represent the tree as a flat list which we don't want to do. In our discussion we did feel that searching by address would make sense as an enhancement and are taking a look at that.

**Comment by Spaark84** [comment]
On most MCUs the registers of a periperal are located in a contiguous memory block, hence I don't think the registers have to be shown in a flat list when sorting them by address.

Anyway, it would already be helpful if one could sort the fields of the registers by bit position, which I think can certainly be realized.

**Comment by benmcmorran** [comment]
@Spaark84 Sorting by address is now available in the pre-release version of Embedded Tools.

![image](https://user-images.githubusercontent.com/6981284/200450774-f8401d24-fe31-4b97-bcdb-f99180126dd6.png)

You can switch to the pre-release channel by clicking this icon in the VS Code Marketplace.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/6981284/200450908-928b43f9-be7d-4e00-94ab-10538ec33db8.png">

Let us know how it works for you! If things look good, this functionality will be included in the next release of the Embedded Tools extension.

**Comment by Spaark84** [comment]
@benmcmorran Many thanks for working on that issue.

When enabling sort by address, the peripherals are sorted by address as expected. However, the registers and the fields of the registers remain sorted by name. I would expect them to be sorted by address as well.

Also, I noticed that the sort button disappears when a periheral in the tree is expanded.

**Comment by gcampbell-msft** [comment]
@Spaark84 Thanks for the feedback! The sort button shouldn't disappear, is it simply that it moved to the right when a field with a larger name expanded the width of the screen? 

As for the sorting, we implemented it with registers and fields accounted for, so there may be an issue with the sorting. Thanks for letting us know and I will look into it.

**Comment by Spaark84** [comment]
@gcampbell-msft You are right regarding the button. Maybe it would be better to put the button in the title bar of the peripheral view, e.g.:

![image](https://user-images.githubusercontent.com/58564478/201149370-7ad61948-71b3-4804-a527-1907c7b253fc.png)

**Comment by gcampbell-msft** [comment]
@Spaark84 Thanks for checking, we'll get on it and hopefully have a fix in pre-release by tomorrow, or early next week at the latest. 👍

**Comment by benmcmorran** [comment]
This issue is fixed in version 0.5.0 of the extension, which is now available in the VS Code Marketplace. Thanks again for your feedback!
