### ISSUE TITLE
Share a roadmap for the development

### ISSUE THREAD

**Issue by escherstair** [microsoft/vscode-embedded-tools#11]
This project seems very promising, but it's not clear if it's heavily developed or not.
Moreover it's not clear if either the community can contribute or it's developed only by MS.

Is it possible to share a roadmap for the development?

Thanks

**Comment by aleun** [comment]
> Is it possible to share a roadmap for the development?

This extension is under active development, but we don't currently have a public roadmap to share, although this is something we are considering for the future.

> Moreover it's not clear if either the community can contribute or it's developed only by MS.

This is a closed-source extension, so we aren't taking contributions from the community. I understand this may not be the answer you were hoping for, but I hope you do understand. We appreciate the feedback.
