### ISSUE TITLE
View freeRTOS timers

### ISSUE THREAD

**Issue by jancoow** [microsoft/vscode-embedded-tools#12]
Type: Feature Request

While we can view running threads with this extension, it would be great to view freeRTOS running timers too.

**Comment by gcampbell-msft** [comment]
Hi @jancoow, thanks for the feedback! You should be able to see that information, we actually support all of the following views:
- Threads
- Queues
- Timers
- Semaphores
- Mutexes
- Eventflags
- Blockpools
- Bytepools

However, this is not entirely obvious in VSCode. You can access these views by first opening the Embedded Tools: RTOS Viewer window, and then opening the command pallete and searching for the above strings, i.e. Press Ctrl-Shift-P to open the command pallete and type in "Timers", a command should appear and this will allow you to view other FreeRTOS objects!

Let me know if this functionality isn't appearing for you.
