### ISSUE TITLE
No valid SVD filepath

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-embedded-tools#15]
![image](https://user-images.githubusercontent.com/25566498/182752458-7af48f39-7f7a-426d-8c74-ec97daa85f75.png)

my test svd：
[test.txt](https://github.com/microsoft/vscode-embedded-tools/files/9256275/test.txt)
my launch
```
"svdPath":"./test.svd",
```

**Comment by gcampbell-msft** [comment]
@hongshui3000 Make sure to set an explicit path to the SVD file, rather than a relative path. Let me know if this fixes your issue!

**Comment by hongshui3000** [comment]
yes it works.thanks

**Comment by benmcmorran** [comment]
Thanks for confirming! I'm closing the issue as resolved.
