### ISSUE TITLE
ST import doesn't handle "Exclude from build"

### ISSUE THREAD

**Issue by nergnezor** [microsoft/vscode-embedded-tools#29]
Files excluded in .cproject (<sourceEntries><entry **excluding="foo.c"|"bar.c"**></sourceEntries>) are still included in generated st-project.cmake

**Comment by robotdad** [comment]
We have a key contributor out right now on this, we should be able to look into this next week.

**Comment by benmcmorran** [comment]
This issue is fixed in version 0.5.0 of the extension, which is now available in the VS Code Marketplace. Thanks again for your feedback!
