### ISSUE TITLE
Add Serial monitor over TCP/IP

### ISSUE THREAD

**Issue by pranjalchanda08** [microsoft/vscode-embedded-tools#32]
Type: Feature Request

It would be nice to have a Serial monitor that can connect to a TCP/IP pipe and perform a 2 way communication over the network. This would help people doing remote debugging.

**Comment by gcampbell-msft** [comment]
@pranjalchanda08 Could you please move this issue to the Serial Monitor extension repository? https://github.com/microsoft/vscode-serial-monitor

Additionally, we have support for this! Switch the "mode" to TCP, and you can do exactly what you want!

![image](https://user-images.githubusercontent.com/86264750/211839460-d8efeb7a-1475-467b-ba82-89a0226a42e9.png)
