### ISSUE TITLE
Add path to STM32CubeCL for MacOS

### ISSUE THREAD

**Issue by matsuev** [microsoft/vscode-embedded-tools#38]
Type: Feature Request

Append path "/opt/ST/STM32CubeCLT/GNU-tools-for-STM32/bin/" into template file gcc-arm-none-eabi.cmake.
It's default installation path for STM32CubeCLT on MacOS.

**Comment by benmcmorran** [comment]
This path has been added to the pre-release channel on the VS Code marketplace. You can switch to the pre-release channel in VS Code.

![prerelease](https://user-images.githubusercontent.com/6981284/210019479-b5a7c09b-1ed5-4fd4-a251-bae5aaab040a.png)

**Comment by benmcmorran** [comment]
The new path is now available in the official 0.7.0 release.

**Comment by minamulhaq** [comment]
![Image](https://github.com/user-attachments/assets/13577305-3f3d-43cd-8a10-00e1569688a5)

![Image](https://github.com/user-attachments/assets/1e85c3a3-eb6d-4589-afed-a9ab52f08624)




Vscode can't find cube clt
