### ISSUE TITLE
How to find STM32CubeIDE？

### ISSUE THREAD

**Issue by luxun59** [microsoft/vscode-embedded-tools#45]
Pop-up error window ``Could not find path to "arm-none-eabi-gdb". Ensure STM32CubeIDE is installed.``

**Comment by benmcmorran** [comment]
Currently (version 0.7.0) the extension searches for `arm-none-eabi-gdb` in a few fixed well-known locations. There's a feature request that we are investigating to support custom ST tool paths (#43). Can you verify that your ST installation is on one of these paths?

```
/ST/STM32CubeCLT/STM32CubeCLT/GNU-tools-for-STM32/bin/arm-none-eabi-gdb.exe
/ST/STM32CubeIDE_*/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin/arm-none-eabi-gdb.exe
/opt/st/stm32cubeide_*/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin/arm-none-eabi-gdb
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin/arm-none-eabi-gdb
```
