### ISSUE TITLE
The selector to choose a .cproject file to import only shows directories inside a dev container

### ISSUE THREAD

**Issue by lukas-lang** [microsoft/vscode-embedded-tools#58]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 20.04 Dev container running on Windows 11
- VS Code Version: 1.78.2
- Embedded Tools Extension Version: 0.7.0
- Target embedded device: -
- RTOS version: -
- Other extensions you installed (and if the issue persists after disabling them): -
- A clear and concise description of what the bug is.

**To Reproduce**
1. Create & open a dev container
2. Copy a project including the `.cproject` file into the dev container
3. Select the "Embedded Tools: Create project from ST project
4. Observe the file selector only showing directories:
  ![image](https://github.com/microsoft/vscode-embedded-tools/assets/33105866/d8159986-1544-4922-b010-b4bfaaf6c0ce)

**Expected behavior**
I should be able to simply select the .cproject file, rather than having to manually type `.cproject` at the end of the path

**Comment by benmcmorran** [comment]
Thanks for the report. This extension is simply using [`vscode.window.showOpenDialog()`](https://code.visualstudio.com/api/references/vscode-api#window.showOpenDialog) from the VS Code API, so if you're seeing issues with file selection inside a devcontainer I'd open an issue on the main [VS Code issue tracker](https://github.com/microsoft/vscode/issues).
