### ISSUE TITLE
SVD Editor

### ISSUE THREAD

**Issue by arietto** [microsoft/vscode-embedded-tools#9]
The Embedded Tools extension provides a register viewer for CMSIS-SVD files. I've opened svd file, but it has been treated as an ordinary XML. How can I activate alternative view for this file? I mean a sort of SVD editor: https://github.com/dmitrystu/svd_editor

**Comment by aleun** [comment]
Hi @arietto. This extension provides a Peripheral View for accessing peripherals during a debug session, but it does not currently have support for editing the SVD files themselves, which sounds like what you're looking for. It's not currently on our backlog to add this support, but I'll keep this issue open as a place for the community to vote.

**Comment by robotdad** [comment]
We've considered this, however improving editing of svd files isn't in scope of what we're pursuing with this extension. I've looked but have not found another extension focused on viewing of the svd files themselves.
